#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Feed-Find
Version  : 0.07
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BT/BTROTT/Feed-Find-0.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BT/BTROTT/Feed-Find-0.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-feed-perl/libxml-feed-perl_0.53+dfsg-1.debian.tar.xz
Summary  : 'Syndication feed auto-discovery'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Feed-Find-license
Requires: perl-Feed-Find-man
Requires: perl(Class::ErrorHandler)
Requires: perl(Encode::Locale)
Requires: perl(HTML::Parser)
Requires: perl(HTTP::Date)
Requires: perl(HTTP::Request)
Requires: perl(LWP)
Requires: perl(Module::Install)
Requires: perl(Try::Tiny)
Requires: perl(URI)
BuildRequires : perl(Class::ErrorHandler)
BuildRequires : perl(Encode::Locale)
BuildRequires : perl(HTML::Parser)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(LWP)
BuildRequires : perl(Module::Install)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(URI)

%description
NAME
Feed::Find - Syndication feed auto-discovery
SYNOPSIS
use Feed::Find;
my @feeds = Feed::Find->find('http://example.com/');

%package license
Summary: license components for the perl-Feed-Find package.
Group: Default

%description license
license components for the perl-Feed-Find package.


%package man
Summary: man components for the perl-Feed-Find package.
Group: Default

%description man
man components for the perl-Feed-Find package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Feed-Find-0.07
mkdir -p %{_topdir}/BUILD/Feed-Find-0.07/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Feed-Find-0.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Feed-Find
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Feed-Find/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Feed/Find.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Feed-Find/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Feed::Find.3
